- hosts: master
  gather_facts: False
  vars:
    sha1_pass_jupyter: "default"
  tasks:
    
    - name: template jupyter deployment file
      template:
        src: jupyter-deployment-template.j2
        dest: /tmp/jupyter_deployment.yml
    
    - name: deploy jupyter
      command: >
        kubectl
        apply
        -f /tmp/jupyter_deployment.yml
