- hosts: master
  gather_facts: False
  vars:
    sha1_pass_jupyter: "default"
  tasks:
    - template:
        src: template.j2
        dest: /tmp/jupyter_deployment.yml
    - command: >
        kubectl
        apply
        -f /tmp/jupyter_deployment.yml
