---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-volume-small-for-jupyter
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: gluster-server
    path: shared-volume
    readOnly: false
