---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: phenomenal_claim
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: gluster-server
    path: shared-volume
    readOnly: false
