---
- hosts: master
  gather_facts: False
  tasks:
    - name: add galaxy repo
      become: yes
      command: >
        helm repo add galaxy-helm-repo 
        https://pcm32.github.io/galaxy-helm-charts
      
    - name: install galaxy
      become: yes
      command: >
        helm install 
        --set use_ingress="yes",domain="{{ domain }}",external_ingress_controller="yes"
        galaxy-helm-repo/galaxy-postgres-chart
