---
- hosts: master
  gather_facts: False
  tasks:
    - name: add galaxy repo
      command: >
        helm repo add galaxy-helm-repo
        https://pcm32.github.io/galaxy-helm-charts
        
    # remove version until stable:--version "{{ galaxy_chart_version }}"
    - name: install galaxy
      command: >
        helm upgrade --install
        --set galaxy_image_tag="{{ galaxy_image_tag }}",use_ingress="yes",domain="{{ domain }}",external_ingress_controller="yes",galaxy_admin_email="{{ galaxy_admin_email }}",galaxy_admin_password="{{ galaxy_admin_password }}",galaxy_api_key="{{ galaxy_api_key }}",postgres.db_password="{{ galaxy_admin_password }}",galaxy_pvc="{{ galaxy_pvc }}",postgres.postgres_pvc="{{ postgres_pvc }}",galaxy_create_pvc="false"
        "galaxy-{{ galaxy_chart_version }}" galaxy-helm-repo/galaxy
