---
- hosts: master
  gather_facts: False
  tasks:
    - name: add jupyter repo
      become: yes
      command: >
        helm repo add phenomenal-helm
        https://phnmnl.github.io/helm-charts
      
    - name: install jupyter
      become: yes
      command: >
        helm install 
        --set passwd_jupyter="{{ jupyter_password }}",use_ingress="yes",domain="{{ domain }}",external_ingress_controller="yes",pvc_exists="yes",jupyter_pvc="phenomenal-claim"
        phenomenal-helm/jupyter
