- hosts: master
  gather_facts: False
  tasks:
   
    - name: template phenomenal-pvc configuration
      become: yes
      template:
        src: phenomenal-pvc.yml
        dest: "/etc/kubenow/yaml/phenomenal-pvc.yml"
    
    - name: create phenomenal-pvc
      command: >
        kubectl apply -f
        /etc/kubenow/yaml/phenomenal-pvc.yml
